#!/bin/bash
#Checkout and compile REDUX repositories from source.android.com

SOURCE_FOLDER=/Volumes/HyperDroidWorkspace

#Create project folder
if [ ! -d $SOURCE_FOLDER ]
then
    mkdir $SOURCE_FOLDER
fi

cd $SOURCE_FOLDER

#clean old compiled files, there can be new stuff!
make installclean
make clean

#Copy buildspec for Desire (until I figure out way to build directly for HD2)
cp vendor/redux/products/leo.mk ./buildspec.mk

#setup compiling environment and build images
cd $SOURCE_FOLDER
. build/envsetup.sh

lunch htc_leo-user
make -j4 redux

#get to compiled folder
cd $SOURCE_FOLDER/out/target/product/leo/
echo 'Your files ready for flashing are here:'
ls *.zip